modLoader="javafml"
loaderVersion="[32,)"
logoFile="logo.png" #optional
issueTrackerURL="https://github.com/minecraftabnormals/Upgrade-Aquatic/issues"
license="https://github.com/minecraftabnormals/Upgrade-Aquatic/blob/master/LICENSE.txt"

[[mods]]
    modId="upgrade_aquatic"
    namespace="upgrade_aquatic"
    version="${file.jarVersion}"
    displayName="Upgrade Aquatic"
    authors="SmellyModder, Bagel, Cameron, Five"
    description='''A mod that improves upon the content of 1.13 Update Aquatic.'''
    displayURL=""

[[dependencies.upgrade_aquatic]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.88,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.upgrade_aquatic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.upgrade_aquatic]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[2.1.0,)"
    ordering="AFTER"
    side="BOTH"
